### PR TITLE
Update elliptic_hyperbolic_lcs_details.m

### PR DESCRIPTION
**Pull request by 1520588207**

### CODE REVIEW

**Comment by jeixav** [comment]
Looks good; thank you! Should probably also update https://github.com/jeixav/LCS-Tool/blob/master/demo/ocean_dataset/elliptic_hyperbolic_lcs.m and https://github.com/jeixav/LCS-Tool/blob/master/demo/ocean_dataset/flow_animation.m.

**Comment by 1520588207** [comment]
@jeixav 
i have try delete the boundry condition in https://github.com/jeixav/LCS-Tool/blob/master/demo/ocean_dataset/elliptic_hyperbolic_lcs.m ,it can also have the fine result,but  https://github.com/jeixav/LCS-Tool/blob/master/demo/ocean_dataset/flow_animation.m. can't run even if i didn't change the conditon.
 in additon,can the method be used in some other area? whether the original data have some restrict?i have try use the ofes data(numerical model data)in some other place .but when i do the eig() ,program has errors.matlab prompt that it  have many NaN.

**Comment by jeixav** [comment]
I have no errors with [flow_animation.m](https://github.com/jeixav/LCS-Tool/blob/master/demo/ocean_dataset/flow_animation.m) @tuxication fixed a few problems in #12. Have you pulled that commit?

**Comment by 1520588207** [comment]
flow_animation.m also can delete the conditons.i have pull requests.

**Pull request merged**
